### PR TITLE
box and shadow

### LINKED ISSUE #3: CSS for boxes
CSS for rounded boxes with rounded drop shadow

### PR DESCRIPTION
**Pull request by lopezelpesado**
Closes #3

### CODE REVIEW

**Comment by lopezelpesado** [comment]
Here's what the boxes look like: 
image

**Review by cem-al — COMMENTED** [review]
Looks good, less blur?

**Review by cem-al — CHANGES_REQUESTED** [review]
Remove blur please

**Review by cem-al — APPROVED** [review]
Thank you

**Pull request merged**
